# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-23 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_apps', '0002_auto_20190822_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
